project_id = "pzrfjartgcurrjfnqflr"

[functions.google-calendar-auth]
verify_jwt = false

[functions.sync-google-calendar]
verify_jwt = false

[functions.create-calendar-event]
verify_jwt = false

[functions.delete-calendar-event]
verify_jwt = false
